media:
  input: public/uploads
  output: /uploads

content:
  - name: how_to
    label: How To
    type: group
    items:
      - name: how_to_clean_up_repair
        label: Clean Up & Repair
        type: collection
        path: content/how-to/clean-up-repair
        filename:
          template: "{primary}.md"
          field: create
        view:
          fields: [title, categories, author, date, draft]
          primary: title
          sort: [date, title]
          search: [title, author, body]
          default:
            sort: date
            order: desc
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: categories
            label: Categories
            type: select
            list: true
            required: true
            default: [clean-up-repair]
            options:
              - clean-up-repair
              - optimize-improve
              - privacy-security
              - files-folders
              - system-tools
          - name: author
            label: Author
            type: string
          - name: date
            label: Publish Date
            type: date
            required: true
          - name: excerpt
            label: Excerpt
            type: text
          - name: featured_image
            label: Featured Image
            type: image
          - name: reading_time
            label: Reading Time
            type: string
          - name: draft
            label: Draft
            type: boolean
            default: false
          - name: body
            label: Body
            type: rich-text

      - name: how_to_optimize_improve
        label: Optimize & Improve
        type: collection
        path: content/how-to/optimize-improve
        filename:
          template: "{primary}.md"
          field: create
        view:
          fields: [title, categories, author, date, draft]
          primary: title
          sort: [date, title]
          search: [title, author, body]
          default:
            sort: date
            order: desc
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: categories
            label: Categories
            type: select
            list: true
            required: true
            default: [optimize-improve]
            options:
              - clean-up-repair
              - optimize-improve
              - privacy-security
              - files-folders
              - system-tools
          - name: author
            label: Author
            type: string
          - name: date
            label: Publish Date
            type: date
            required: true
          - name: excerpt
            label: Excerpt
            type: text
          - name: featured_image
            label: Featured Image
            type: image
          - name: reading_time
            label: Reading Time
            type: string
          - name: draft
            label: Draft
            type: boolean
            default: false
          - name: body
            label: Body
            type: rich-text

      - name: how_to_privacy_security
        label: Privacy & Security
        type: collection
        path: content/how-to/privacy-security
        filename:
          template: "{primary}.md"
          field: create
        view:
          fields: [title, categories, author, date, draft]
          primary: title
          sort: [date, title]
          search: [title, author, body]
          default:
            sort: date
            order: desc
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: categories
            label: Categories
            type: select
            list: true
            required: true
            default: [privacy-security]
            options:
              - clean-up-repair
              - optimize-improve
              - privacy-security
              - files-folders
              - system-tools
          - name: author
            label: Author
            type: string
          - name: date
            label: Publish Date
            type: date
            required: true
          - name: excerpt
            label: Excerpt
            type: text
          - name: featured_image
            label: Featured Image
            type: image
          - name: reading_time
            label: Reading Time
            type: string
          - name: draft
            label: Draft
            type: boolean
            default: false
          - name: body
            label: Body
            type: rich-text

      - name: how_to_files_folders
        label: Files & Folders
        type: collection
        path: content/how-to/files-folders
        filename:
          template: "{primary}.md"
          field: create
        view:
          fields: [title, categories, author, date, draft]
          primary: title
          sort: [date, title]
          search: [title, author, body]
          default:
            sort: date
            order: desc
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: categories
            label: Categories
            type: select
            list: true
            required: true
            default: [files-folders]
            options:
              - clean-up-repair
              - optimize-improve
              - privacy-security
              - files-folders
              - system-tools
          - name: author
            label: Author
            type: string
          - name: date
            label: Publish Date
            type: date
            required: true
          - name: excerpt
            label: Excerpt
            type: text
          - name: featured_image
            label: Featured Image
            type: image
          - name: reading_time
            label: Reading Time
            type: string
          - name: draft
            label: Draft
            type: boolean
            default: false
          - name: body
            label: Body
            type: rich-text

      - name: how_to_system_tools
        label: System Tools
        type: collection
        path: content/how-to/system-tools
        filename:
          template: "{primary}.md"
          field: create
        view:
          fields: [title, categories, author, date, draft]
          primary: title
          sort: [date, title]
          search: [title, author, body]
          default:
            sort: date
            order: desc
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: categories
            label: Categories
            type: select
            list: true
            required: true
            default: [system-tools]
            options:
              - clean-up-repair
              - optimize-improve
              - privacy-security
              - files-folders
              - system-tools
          - name: author
            label: Author
            type: string
          - name: date
            label: Publish Date
            type: date
            required: true
          - name: excerpt
            label: Excerpt
            type: text
          - name: featured_image
            label: Featured Image
            type: image
          - name: reading_time
            label: Reading Time
            type: string
          - name: draft
            label: Draft
            type: boolean
            default: false
          - name: body
            label: Body
            type: rich-text

  - name: windows_tips
    label: Windows Tips
    type: collection
    path: content/windows-tips
    filename:
      template: "{primary}.md"
      field: create
    view:
      fields: [title, categories, author, date, draft]
      primary: title
      sort: [date, title]
      search: [title, author, body]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: categories
        label: Categories
        type: select
        list: true
        required: true
        default: [windows-tips]
        options:
          - windows-tips
      - name: author
        label: Author
        type: string
      - name: date
        label: Publish Date
        type: date
        required: true
      - name: excerpt
        label: Excerpt
        type: text
      - name: featured_image
        label: Featured Image
        type: image
      - name: reading_time
        label: Reading Time
        type: string
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text

  - name: hardware
    label: Hardware
    type: collection
    path: content/hardware
    filename:
      template: "{primary}.md"
      field: create
    view:
      fields: [title, categories, author, date, draft]
      primary: title
      sort: [date, title]
      search: [title, author, body]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: categories
        label: Categories
        type: select
        list: true
        required: true
        default: [hardware]
        options:
          - hardware
      - name: author
        label: Author
        type: string
      - name: date
        label: Publish Date
        type: date
        required: true
      - name: excerpt
        label: Excerpt
        type: text
      - name: featured_image
        label: Featured Image
        type: image
      - name: reading_time
        label: Reading Time
        type: string
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
